apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openvalidation-rest
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: openvalidation-rest
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: openvalidation-rest
          image: openvalidationdockerrepo.azurecr.io/openvalidation/rest:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: openvalidation-rest
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: openvalidation-rest
